# всегда добавлять точку с запятой (;) в конце каждой инструкции
semi: true

# Все строки будут форматироваться с использованием одинарных кавычек (') вместо двойных (").
singleQuote: true

# Ширина табуляции
tabWidth: 4

# Максимальная длина строки
printWidth: 80

# добавлять завершающие запятые
trailingComma: es5
